#!/bin/bash
###############################################################################
# Pre-removal script for GenAI Research (Debian/Ubuntu)
###############################################################################

set -e

# Stop and disable service
if systemctl is-active --quiet genai_research; then
    systemctl stop genai_research
fi

if systemctl is-enabled --quiet genai_research; then
    systemctl disable genai_research
fi

exit 0
